steps:
  - name: node:16.6.1
    entrypoint: node
    args: ['-v']
  - name: node
    entrypoint: npm
    args: ['-v']
  - name: node
    entrypoint: npm
    args: ['init']
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'test:unit', '--ws']